import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import NavBar from "./NavBar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased bg-white text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100">
        <Providers>
          <NavBar />
          {children}
          <Toaster richColors position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
